# Generated by Django 5.1.7 on 2025-12-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapist', '0003_conversation_chatmessage_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='emotion_label',
            field=models.CharField(default='Neutral', max_length=50),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
